"""добавил таблицу сенсеров

Revision ID: 791eccc3c584
Revises: aaa02a19e054
Create Date: 2025-11-21 17:58:09.794206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '791eccc3c584'
down_revision: Union[str, Sequence[str], None] = 'aaa02a19e054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('system_id', sa.Uuid(), nullable=True),
    sa.Column('sensor_name', sa.TEXT(), nullable=False),
    sa.Column('state', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'systems', ['system_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'systems', type_='unique')
    op.drop_table('sensors')
    # ### end Alembic commands ###
