"""добавил таблицу состояний

Revision ID: 82ad7eb7f866
Revises: 791eccc3c584
Create Date: 2025-11-25 17:35:40.309800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ad7eb7f866'
down_revision: Union[str, Sequence[str], None] = '791eccc3c584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors_state',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('sensors', 'state')
    op.drop_column('sensors', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('description', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sensors', sa.Column('state', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('sensors_state')
    # ### end Alembic commands ###
