"""базовая таблица

Revision ID: aaa02a19e054
Revises: 
Create Date: 2025-11-20 18:57:35.423933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa02a19e054'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('system_name', sa.TEXT(), nullable=False),
    sa.Column('system_key', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('systems')
    # ### end Alembic commands ###
