"""create_db

Revision ID: ab981a371eec
Revises: 
Create Date: 2025-11-26 15:34:22.518392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab981a371eec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('system_name', sa.TEXT(), nullable=False),
    sa.Column('system_key', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_key')
    )
    op.create_table('sensors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('system_id', sa.Uuid(), nullable=True),
    sa.Column('sensor_name', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensors_state',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensors_state')
    op.drop_table('sensors')
    op.drop_table('systems')
    # ### end Alembic commands ###
